### ISSUE TITLE
[MOD COMPATIBILITY] Crashes when Pause menu is displayed due to conflict with ImmediateFast Mod

### ISSUE THREAD

**Issue by takexaz** [42atomys/fabric-advancementinfo-reloaded#1]
### Bug
When used with [ImmediateFast](https://modrinth.com/mod/immediatelyfast) Mod, when Esc is pressed during play, it crashes before the Pause menu appears.

### Crash Report
delete

**Comment by 42atomys** [comment]
Hey, thanks for using the mod, I will check that quick 💜

**Comment by laurin-op** [comment]
Same behaviour when using [ModMenu](https://modrinth.com/mod/modmenu), seems to be the same Exception

[Crash Report](https://mclo.gs/YkxUpga)

**Comment by 42atomys** [comment]
@L40P The incompatibility are resolved in **v0.2.0**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

Thanks for your crashlogs 👍
