### ISSUE TITLE
Color display behavior in description of advancement is different from vanilla

### ISSUE THREAD

**Issue by ItzSkyReed** [42atomys/fabric-advancementinfo-reloaded#11]
in vanilla, if the exact color of the advancement is not specified in the description of the advancement, then the color is inherited from the frame of advancement, but in the description of the criteria, when pressed, it remains gray (screenshot 1), which should not be, as it seems to me, and the color should match the color of the advancement description (screenshot 2).
frame color is dark_purple (#AA00AA) for challenges and green (#55FF55) for task/goal

Screenshot1
![image](https://github.com/user-attachments/assets/1f1805c0-1af9-4223-9ce1-037740e042f2)

Screenshot2
![image](https://github.com/user-attachments/assets/d2bd85b4-d5c4-4cf9-9da9-5e5c1fe79b2b)

**Comment by 42atomys** [comment]
Hi, the goal is to allow full customization for developers with a future API.
The idea for the future is to set specific colors for achievement names and to create an icon or badge, I don't reach this step actually ^^

**The bug I noticed is that the gray color on a light background significantly reduces the readability of the description.**

**Comment by ItzSkyReed** [comment]
> The bug I noticed is that the gray color on a light background significantly reduces the readability of the description.

I didn't mean that exactly, I meant more that if the color of the advancement description is not specified, then it would be better to make it the same as the color of the name of this advancement, and not gray.

**Comment by 42atomys** [comment]
Oh ok, thanks for the clarification I miss it, that a good idea yes

**Comment by 42atomys** [comment]
Hi again, the issue are resolved in **v0.4.1**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

See you soon !

**Comment by ItzSkyReed** [comment]
Thanks!
