### ISSUE TITLE
Add a setting to configure the opacity of footer/header/criteria area (with different settings in the config)

### ISSUE THREAD

**Issue by ItzSkyReed** [42atomys/fabric-advancementinfo-reloaded#12]
![image](https://github.com/user-attachments/assets/6cca34c8-488d-4613-a3ab-228f07276dfe)
Because sometimes it is very difficult to read some text, such as here (I mean "The following mobs..."

**Comment by 42atomys** [comment]
I link this issue as duplicated of #11, I will resolve both in one !
