### ISSUE TITLE
Can't load icon of the mod in ModMenu

### ISSUE THREAD

**Issue by Alwnor** [42atomys/fabric-advancementinfo-reloaded#2]
![Screenshot_9](https://github.com/42atomys/fabric-advancementinfo-reloaded/assets/89651971/060bc6f9-5761-4606-afde-14cd2663068c)
Screenshot done in Logs of Modrinth Launcher

**Comment by 42atomys** [comment]
Thanks for the report, I will include that in the next release

**Comment by 42atomys** [comment]
@Alwnor The icon are back in **v0.2.0**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

Thanks for your report 👍
