### ISSUE TITLE
Neoforge/Forge Accessibility

### ISSUE THREAD

**Issue by ThreeAccounts** [42atomys/fabric-advancementinfo-reloaded#22]
Would be nice to have a Neoforge/Forge accesibility

**Comment by 42atomys** [comment]
Hi @ThreeAccounts thanks for opening this issue, I will take a lot soon to add support !

**Comment by 42atomys** [comment]
Hi there
Multi-platform support is in beta and available on [Modrinth](https://modrinth.com/mod/advancements-reloaded/versions) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/advancements-reloaded)!
