### ISSUE TITLE
Feature Request: Attempt to translate some criteria.

### ISSUE THREAD

**Issue by iAkariAk** [42atomys/fabric-advancementinfo-reloaded#23]
In my view, we could mitigate this to some extent by using something like the following approach, inspired by https://github.com/MarkusBordihn/BOs-Advancements-Tracker/blob/5720ea2dd3c3ed73faf1f2b13ffb0e6918104828/src/main/java/de/markusbordihn/advancementstracker/client/advancements/AdvancementEntryProgress.java#L193

```java
translateOrNull("item." + namespace + "." + criteriaName)
    .or(() -> translateOrNull("block." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("entity." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("enchantment." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("effect." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("biome." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("dimension." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("mob." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("potion." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("recipe." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("advancement." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("structure." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("statistic." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("loot_table." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("block_state." + namespace + "." + criteriaName))
    .or(() -> translateOrNull("biome_category." + namespace + "." + criteriaName))
    .orElse(Text.of(criteriaName));
```
Although https://github.com/42atomys/fabric-advancementinfo-reloaded/issues/14 is more flexible, it requires a lot of effort, and it could be made into a configurable feature.

**Comment by 42atomys** [comment]
Hi,

I don't know this mod https://github.com/MarkusBordihn/BOs-Advancements-Tracker and looks like I wanna create for the future of the mod. impressive works from MarkusBordihn !

I currently on the migration of the mod to support all loaders (Fabric, Quilt, NeoForge), after this migration I will continue to implement feature ! 🏃 

Thanks for the share and your input, I will dive into it when I start the development of #14 !

**Comment by 42atomys** [comment]
Following on #14 (information from this proposal and final solution are present on it)🚀

**Comment by 42atomys** [comment]
This is now available on modrinth 🎉  ! https://modrinth.com/mod/advancements-reloaded

If you are a resource pack / data pack maker, that will maybe help you : https://github.com/42atomys/mc-advancements-reloaded/wiki/Translation

See you !
