### ISSUE TITLE
feature request:  Click Advancements from chat to take you directly to the advancement.

### ISSUE THREAD

**Issue by StoneLegion** [42atomys/fabric-advancementinfo-reloaded#27]
### Describe the Request

A Mod like this but one that works or rather built into your mod. 

https://www.curseforge.com/minecraft/mc-mods/clickable-advancements

The idea is you click the advancement in chat like you do in many MMO's and it takes you right to the location / page. The clickable mod itself brings up the old interface rather then your interface, so it does not sadly work the way one would like.

### Modloader Type

Neoforge

### Modloader Version

1.21.1

**Comment by 42atomys** [comment]
Hi, thanks for your feedback, this issue are already addressed here #16 and currently in discussion between me and the clickable-advancement mod creator :)

I close this issue as duplicate
