### ISSUE TITLE
bug: how to revert the order to use both 2 lines?

### ISSUE THREAD

**Issue by VaporeonScripts** [42atomys/fabric-advancementinfo-reloaded#28]
### Describe the Bug

they are all on the bottom line with goofy order,but id like to have it as before 0.6.0 update, what can i do?

### Steps to Reproduce

get latest neoforge 1.21.1 update

### Expected Behavior

have the order it had before

### Screenshots

a

### Modloader Type

Neoforge

### Modloader Version

latest

### Mod Version

latest

### Log Output

```shell
a
```

### Additional Context

a

**Comment by VaporeonScripts** [comment]
also how do i access config from config folder? cuz editing stuff in game makes the game crash

**Comment by 42atomys** [comment]
@VaporeonScripts hi, can you provide me screenshots, and logs from crash please ? 
That will help me to give you help and/or fix issue !

**Comment by VaporeonScripts** [comment]
alright, ima send the crash log, then the pic of the order,cuz it seems that im unable to see some advancements that i could see before

**Comment by VaporeonScripts** [comment]
https://mclo.gs/YaOidsF

**Comment by VaporeonScripts** [comment]
also seems to be unable to generate config

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/b0e1d32f-4c32-4298-a306-21e2b72f1ec1)
now it seems like it also uses top bar, btw how can i make them straight, and not up and down?

**Comment by 42atomys** [comment]
Thanks for the extra context 🙏  Really appreciated ! 

Effectively disorder.. a kind of.. "order" :trollface: 

I will check that !

**Comment by VaporeonScripts** [comment]
alright,ty!!

**Comment by 42atomys** [comment]
@VaporeonScripts, im back

- For the visual issue, That the mod obviously.
- For the crash that seems to be on your side, the crash come from `mojang/Narrator` due to missing `flite` library required by the narrator. As you are on archlinux you can try to install `flite` and restart prismalauncher !

**Comment by VaporeonScripts** [comment]
is flite a mod or what? cuz i dont really understand why narrator would be required fr

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/fe83efc8-a656-4275-aa87-e6907b495750)

**Comment by VaporeonScripts** [comment]
if im right flite should be a package?

**Comment by VaporeonScripts** [comment]
i installed it, ima see how it goes

**Comment by VaporeonScripts** [comment]
https://mclo.gs/nLPbtcz with flite (assuming its the one from sudo pacman -S flite)

**Comment by VaporeonScripts** [comment]
i did not reboot btw

**Comment by VaporeonScripts** [comment]
narrator works altough still crashes

**Comment by 42atomys** [comment]
Thanks for your time ! The narrator Issue are resolved well, and now I can see the real source of the crash 💥 

I will works on the fix starting monday !

**Comment by VaporeonScripts** [comment]
alright

**Comment by 42atomys** [comment]
I fix the crash but maybe another UI mod cause another error. When you will have install the  `0.6.1`, if you have another issue, please re-open a new one 🙏 💜

**Comment by VaporeonScripts** [comment]
Alright,thanks
