### ISSUE TITLE
bug: Crash when using lastest advancement reloaded update

### ISSUE THREAD

**Issue by Kloytz** [42atomys/fabric-advancementinfo-reloaded#29]
### Describe the Bug

After updating from the 0.5 to 0.6 and enterring the advancement tab it just crashed instantly

### Steps to Reproduce

Update to lastest version and open advancement tab

### Expected Behavior

To not crash?

### Modloader Type

Minecraft Forge

### Modloader Version

0.16.7

### Mod Version

0.6.0

### Log Output

```shell
https://mclo.gs/A0BURQR
```

**Comment by 42atomys** [comment]
Hi thanks for the report, I will check

**Comment by 42atomys** [comment]
I fix the crash but maybe another UI mod cause another error. When you will have install the ` 0.6.1`, if you have another issue, please re-open a new one 🙏 💜
