### ISSUE TITLE
bug: Advancement reloaded still crashing while trying to open the advancement tab on newest update

### ISSUE THREAD

**Issue by Kloytz** [42atomys/fabric-advancementinfo-reloaded#35]
### Describe the Bug

Crashes when trying to open advacement tab

### Steps to Reproduce

Update to version 0.6.1
Launch minecraft
Enter a singleplayer world
Open advancement tab

### Expected Behavior

Not to crash?

### Modloader Type

Fabric

### Modloader Version

0.16.7

### Mod Version

0.6.1

### Log Output

```shell
https://mclo.gs/hkKXCSo
```

**Comment by VaporeonScripts** [comment]
same issue
https://mclo.gs/cQczoix

**Comment by 42atomys** [comment]
One of your report are related to the same issue of #36. I tracking it
