### ISSUE TITLE
bug: tab icons do the "samba du brazil"

### ISSUE THREAD

**Issue by Linahun** [42atomys/fabric-advancementinfo-reloaded#37]
### Describe the Bug

The tabs display in an odd fashion off the footer and cover some of the advancement pictures. 
![image](https://github.com/user-attachments/assets/2e671dd7-dcd2-4ed4-ada0-5e214b1a3ba9)

### Steps to Reproduce

My GUI scale is set to 4.  I changed Footer Height to 48 to match the Header Height hoping that would fix it, but it didn't.

### Expected Behavior

The tabs should be placed fully within the footer or header.

### Screenshots

See above under the Bug section.

### Modloader Type

Fabric

### Modloader Version

Prism Loader - Java Fabric 1.21.1

### Mod Version

0.6.10-fabric-1.21.1

### Log Output

```shell
N/A
```

**Comment by 42atomys** [comment]
Hi thanks for the report, can you provide me the configuration file to help to to reproduce this issue ? 

The file are located on your minecraft folder `config/advancements_reloaded.json`

Thanks in advance

**Comment by VaporeonScripts** [comment]
port it to 1.21.1 :sob:

**Comment by Linahun** [comment]
Sorry!  Here is the config:
[advancements_reloaded.json](https://github.com/user-attachments/files/17833457/advancements_reloaded.json)
