### ISSUE TITLE
Clicking an advancement puts your view into the center of the page.

### ISSUE THREAD

**Issue by Terminxa** [42atomys/fabric-advancementinfo-reloaded#4]
This may be intentional but it makes it much harder to view advancements because clicking it sends you back. If this is intended maybe make a toggle to turn it off?
https://github.com/42atomys/fabric-advancementinfo-reloaded/assets/106455196/ff24d76b-56a4-47de-a14d-3e98061352b3

**Comment by 42atomys** [comment]
Hi @TruMiner In fact that is intentional for horizontal but vertically is a bug, thanks for the report !

I will works on it tonight 🔥

**Comment by 42atomys** [comment]
Hi again, the issue are resolved in **v0.2.1**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

Thanks for the report and screen share :rocket:
