### ISSUE TITLE
Custom scroll bars via resource packs sometimes don't work.

### ISSUE THREAD

**Issue by Terminxa** [42atomys/fabric-advancementinfo-reloaded#5]
I made a resource pack that changes the texture of scroll bars, and it seems that the scroll bars in the advancement menu incorrectly stack the texture instead of using the nine slices that all other GUIs use.
Here is an image of how it is supposed to look (comes from the Mod Menu menu):
![image](https://github.com/42atomys/fabric-advancementinfo-reloaded/assets/106455196/daee9653-36e9-4df1-8a54-b7bd276a515a)
Here is an image of how it looks in the Advancements menu:
![image](https://github.com/42atomys/fabric-advancementinfo-reloaded/assets/106455196/390fe83a-8e5a-45a0-9bc8-4a070798e3f6)
I don't think this is a resource pack issue, but if you want to see the resource pack for testing here it is:
[resourcepack.zip](https://github.com/user-attachments/files/16172263/resourcepack.zip)
(Note: the scrollers have special mcmeta files that determine the way it should be split. I don't think these are causing the issues, because when I removed them in my testing, the texture issues in the other GUIs were stretched slightly different and didn't stack like the issue above.)

**Comment by 42atomys** [comment]
The scroll bar are reimplemented from scratch so that's can happen, thanks to provide the resource pack and report the issue, I will check that this night 🐝

**Comment by 42atomys** [comment]
Hi again, the issue are resolved in **v0.2.1**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

Thanks for the resource pack, that is tested with provided .zip and works well now !
