### ISSUE TITLE
[bug] [0.3.0-1.21]option descriptions persist after hovering off the option

### ISSUE THREAD

**Issue by krispyking24** [42atomys/fabric-advancementinfo-reloaded#6]
![image](https://github.com/user-attachments/assets/f5146a94-298c-43a1-ada8-77015bfbb9a2)
![image](https://github.com/user-attachments/assets/23573660-71e1-4d57-b310-e13f86eb50b1)
[video](https://github.com/user-attachments/assets/2f474ad4-2bd3-4c49-8552-f75012db45c6) shows how to achieve the bug

**Comment by 42atomys** [comment]
Hi @krispyking24, this seams to be related to the [ModMenu](https://modrinth.com/mod/modmenu) mod, because is only on ModMenu and not on Achievement page
