### ISSUE TITLE
feat(option): add new background options to have achievement background 

### ISSUE THREAD

**Issue by ItzSkyReed** [42atomys/fabric-advancementinfo-reloaded#9]
> Show background texture of the current advancement tab instead of black background

It will look better, I think

**Comment by 42atomys** [comment]
Hi @ItzSkyReed That can be an easy addition for customization, I will add as an option

Thanks for the idea !

**Comment by 42atomys** [comment]
Hi again, the issue are resolved in **v0.4.0**, available on modrinth right now https://modrinth.com/mod/advancements-reloaded

Thanks again for the proposal

**Comment by ItzSkyReed** [comment]
Nice!
